### ISSUE TITLE
plz

### ISSUE THREAD

**Issue by T0-0Lman** [edencoding/javafx-io#1]
Hello sir, your work and tutorials are great! But can you add query functions to your SQLiteExampleApp? And write a tutorial like other functions? I really want to learn this program from you, if you can, I would be very grateful.

**Comment by edencoding** [comment]
Hi, 

Thanks - glad you enjoy the tutorials!

Can you be a little more specific as to which query functions you mean? Have you taken a look at the CRUDHelper class, which includes queries to read data from the database?

Cheers,

Ed

**Comment by T0-0Lman** [comment]
Thank you for the reply. What I want to express is that after adding person, I can find the corresponding person through the search box and input id or name, etc.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "edencoding/javafx-io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [edencoding/javafx-io] plz (#1)





 
Hi,
 
Thanks - glad you enjoy the tutorials!
 
Can you be a little more specific as to which query functions you mean? Have you taken a look at the CRUDHelper class, which includes queries to read data from the database?
 
Cheers,
 
Ed
